server:
  port: 8081

spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://localhost:3307/bookstore?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root