server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bookstore?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

jwt:
  jwt-key: neil-yang
  token-expired-in: 86400000

